### ISSUE TITLE
Invoking mbsync while one hasn't completed is not great

### ISSUE THREAD

**Issue by ahungry** [dimitri/mbsync-el#9]
This PR adds a mutex to mbsync to ensure only one process for fetching occurs at a time.

Under current conditions without this change, this will force the user to interactively discard or restart the *mbsync* buffer, however running multiple mbsync processes simultaneously will never have a benefit to the user (at least, when they are given identical CLI args).

This PR addresses by ensuring only one runs at a time.

I didn't add the message calls to the mbsync-info channel / function, because the messages are not really debug level, but let the user know something has happened, in what was otherwise a silent function call.

https://github.com/dimitri/mbsync-el/pull/8

**Comment by unhammer** [comment]
That works … though I've been using the following for a while:
    
      (defun get-mbsync-proc ()
        "Get the running mbsync process (or nil if no such)."
        (let ((b (get-buffer "*mbsync*")))
          (and (buffer-live-p b) (get-buffer-process b))))

      (defun safe-mbsync ()
        (interactive)
        (unless (get-mbsync-proc) (mbsync)))

Since the buffer is always named `*mbsync*`, that keeps the logic a bit more local – what do you think?

**Comment by ahungry** [comment]
Looks nice, my use case was wanting to prevent double `f` taps (I used that for my GNUS bind as recommended) from kicking off the process twice, so if that works even if there are 2 quick successive function invocations, looks good to me, whichever you prefer (although I like just getting a message telling me the other is running over switching to the buffer, but ymmv).

**Comment by unhammer** [comment]
Could you try https://github.com/dimitri/mbsync-el/commit/7562e9742d1aaaed3af996a86c1fb17c00661ae3 and see if that solves it?

(Also, I saw you had an unrelated commit there – if you put it in a branch and make a new PR I can merge.)

**Comment by ahungry** [comment]
Looks great and works great, thanks! Making separate PR
